# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171126_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=b'', max_length=96)),
                ('city', models.CharField(default=b'', max_length=96)),
                ('street', models.CharField(default=b'', max_length=96)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(default=b'', max_length=96),
        ),
        migrations.AddField(
            model_name='location',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Meeting'),
        ),
    ]
