# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171201_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Meeting'),
        ),
    ]
